// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace WeatherReport.ios
{
	public partial class AnimationView : UIView
	{
		public AnimationView (IntPtr handle) : base (handle)
		{
		}
	}
}
